/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List requests */
        get: operations["listRequests"];
        put?: never;
        /** Create draft request */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get request detail with approvals */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update request (Draft only) */
        patch: operations["updateRequest"];
        trace?: never;
    };
    "/requests/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit request (Draft -> Pending) */
        post: operations["submitRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve request (Pending -> Approved) */
        post: operations["approveRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject request (Pending -> Rejected) */
        post: operations["rejectRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise request (Rejected -> Draft) */
        post: operations["reviseRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logical delete request (Draft/Rejected -> Deleted) */
        post: operations["deleteRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** @enum {string} */
        RequestStatus: "Draft" | "Pending" | "Approved" | "Rejected" | "Deleted";
        /** @enum {string} */
        ApprovalActionType: "Approved" | "Rejected";
        Request: {
            id: components["schemas"]["Uuid"];
            teamId: components["schemas"]["Uuid"];
            title: string;
            body: string;
            status: components["schemas"]["RequestStatus"];
            createdBy: components["schemas"]["Uuid"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt?: string | null;
        };
        Approval: {
            id: components["schemas"]["Uuid"];
            requestId: components["schemas"]["Uuid"];
            actedBy: components["schemas"]["Uuid"];
            actionType: components["schemas"]["ApprovalActionType"];
            reason?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateRequestBody: {
            title: string;
            body: string;
        };
        UpdateRequestBody: {
            title?: string;
            body?: string;
        };
        DecisionBody: {
            reason?: string;
        };
        ErrorObject: {
            code: string;
            message: string;
            status: number;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorObject"];
        };
        ListRequestsResponse: {
            items: components["schemas"]["Request"][];
            page: number;
            limit: number;
            total: number;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        RequestId: components["schemas"]["Uuid"];
        XActorId: components["schemas"]["Uuid"];
        XTeamId: components["schemas"]["Uuid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRequests: {
        parameters: {
            query: {
                teamId: components["schemas"]["Uuid"];
                status?: components["schemas"]["RequestStatus"];
                from?: string;
                to?: string;
                includeDeleted?: boolean;
                page?: number;
                limit?: number;
            };
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRequestsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                        approvals: components["schemas"]["Approval"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    submitRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    approveRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                        approval: components["schemas"]["Approval"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                        approval: components["schemas"]["Approval"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reviseRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteRequest: {
        parameters: {
            query?: never;
            header: {
                "x-actor-id": components["parameters"]["XActorId"];
                "x-team-id": components["parameters"]["XTeamId"];
            };
            path: {
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["Request"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
